// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRcPUg6idHPLE_fwKviMTulOP5guMU_hw',
    appId: '1:932283109096:web:88e6abe95100fb3462035d',
    messagingSenderId: '932283109096',
    projectId: 'amt-v3',
    authDomain: 'amt-v3.firebaseapp.com',
    storageBucket: 'amt-v3.appspot.com',
    measurementId: 'G-V9H95MBJG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABsj1fcbWRQ1gDYvkJA_e8EJkRv7nD7eM',
    appId: '1:932283109096:android:4fca1ca76dc6e1f362035d',
    messagingSenderId: '932283109096',
    projectId: 'amt-v3',
    storageBucket: 'amt-v3.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGGU1Pm-fPUnYDfgQNtMoOnprMfFhNhXE',
    appId: '1:932283109096:ios:5b64508c6399f71f62035d',
    messagingSenderId: '932283109096',
    projectId: 'amt-v3',
    storageBucket: 'amt-v3.appspot.com',
    iosClientId: '932283109096-kji5qt9b891u2nojpf69jn0633439f7g.apps.googleusercontent.com',
    iosBundleId: 'pink.renard.amt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkN8n1IoXbdkPA0qHJVAuFoXJQInBXzNQ',
    appId: '1:932283109096:web:86e3bc98f701a60e62035d',
    messagingSenderId: '932283109096',
    projectId: 'amt-v3',
    authDomain: 'amt-v3.firebaseapp.com',
    storageBucket: 'amt-v3.appspot.com',
    measurementId: 'G-Q2C156G7P9',
  );

}